# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  aspnetcorewebapi2:
    image: aspnetcorewebapi2
    build:
      context: .
      dockerfile: AspNetCoreWebApi2/Dockerfile
    ports:
      - 90:90
